

name: CI/CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
 
  schedule:
   - cron: 0 8,11,14,17 * * 1-5
   
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 8
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so job can access it
      - name: 🍽️ Get working copy
        uses: actions/checkout@master
        with:
          fetch-depth: 1 

      - name: 🐍 Set up Python 3.8                               
        uses: actions/setup-python@v2                               
        with:                                 
          python-version: '3.8'
      
      - name: install required packages 
        run: python -m pip install -r requirements.txt
      
      - name: execute scripts
        run: python Main.py
        

        
